YORGEABBOTT52 = arm64 armv7
TARGET_IPHONEOS_DEPLOYMENT_VERSION = 7.0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = DarkMusic10_Preferences
DarkMuisc10_Preferences_FILES = Tweak.xm
DarkMusic10_Preferences_LDFLAGS += -Wl,-segalign,4000
DarkMusic10_Preferences_FRAMEWORKS = UIKit

include $(THEOS)/makefiles/tweak.mk
